age=int(input("enter youre age: " ))
age=int(input("enter youre age: " ))
print(age+10)
num1=int(input("enter first num: "))
num2=int(input("enter second num: "))
print(num1+num2)
hieght=float(input("enter youre hieght: "))
print(hieght)
price=float(input("enter price: "))
print(price+5.5)
name=type ("dachi")
age=type("11")
hieght=type("1.56")
name="Nika"
age=15
age=int(input("enter youre age: "))
print(f"hello{name }youre {age } years old")
num1=int(input("enter first num: "))
num2=int(input("enter second num: "))
print(num1*num2)
num1=int(input("enter first num:"  ))
print(num1-3)
age=int(input("enter youre age: "))
print(age+10)
age=type(age)